name: Release Binaries

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-macos-arm64:
    runs-on: macos-14
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest

      - name: Build AgentService (Release)
        run: |
          swift build -c release --package-path AgentService
          bin="$(swift build -c release --package-path AgentService --show-bin-path)"
          mkdir -p dist
          cp "$bin/AgentService" dist/
          tar -czf AgentService-macos-arm64.tar.gz -C dist AgentService

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: AgentService-macos-arm64
          path: AgentService-macos-arm64.tar.gz

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: AgentService-macos-arm64.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

